name: dart_overpass
description: A fork of [flutter_overpass](https://pub.dev/packages/flutter_overpass) written in pure dart.
version: 0.0.1
repository: https://github.com/chrisnorman7/dart_overpass

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  dio: ^5.6.0
  json_annotation: ^4.9.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
